### ISSUE TITLE
feat: Thumbnail Dinamis

### ISSUE THREAD

**Issue by algonacci** [OpenProjects-id/KawanData#16]
- [ ] Perbedaan thumbnail setiap course

**Comment by algonacci** [comment]
![image](https://user-images.githubusercontent.com/86970816/146427682-be472ed2-3787-45ed-ac9e-819360f3f8d6.png)

As you know, this thumbnail of each course are hard-coded.

We need to make it dynamic so the thumbnail can become more suitable according to the course title.

Just contact or mentioned me if you need any assets or design.

**Comment by AaEzha** [comment]
how random the thumbnails are?

are they random by keywords from title or what?

**Comment by algonacci** [comment]
> how random the thumbnails are?
> 
> are they random by keywords from title or what?

As I said, each thumbnail is hard-coded.

I'm thinking to add a new field in the course table and store the image thumbnail so we can call it according to the course title.

Or maybe there is any suggestion? It will be great

**Comment by AaEzha** [comment]
I'm agree that adding a new field is the answer

**Comment by algonacci** [comment]
> I'm agree that adding a new field is the answer

Any suggestion to store the image? I'm thinking something like [Cloudinary](https://cloudinary.com/)

**Comment by algonacci** [comment]
Halo mas @fadila-amin saya assign disini dulu yaa. Temen-temen nanti kalau ada yang berminat untuk bantu kontribusi juga silahkan 😄 

Bisa DM saya di twitter atau mentioned saya disini. Thank you
