### ISSUE TITLE
feat: Authentication

### ISSUE THREAD

**Issue by algonacci** [OpenProjects-id/KawanData#2]
- [x] Fitur register dengan email
- [x] Verifikasi email setelah register
- [x] Fitur login dengan email
- [x] #3

**Comment by AaEzha** [comment]
aku coba kerjakan untuk yg registernya ya.

etapi, butuh verifikasi email dulu kan, ya?

**Comment by algonacci** [comment]
> aku coba kerjakan untuk yg registernya ya.
> 
> etapi, butuh verifikasi email dulu kan, ya?

Boleh mas, approved yaa mungkin nnti bisa dibikinin issue baru ajaa.

Iyaa lebih baik ada verifikasi emailnya mas jadi ga sembarangan daftar pakai email orang lain 😄

**Comment by AaEzha** [comment]
@algonacci yang tanpa verifikasi sih sudah selesai.

mau dimerge dulu atau lanjutin aja verifikasinya?

**Comment by algonacci** [comment]
> @algonacci yang tanpa verifikasi sih sudah selesai.
> 
> mau dimerge dulu atau lanjutin aja verifikasinya?

Boleh dimerge dulu aja

**Comment by AaEzha** [comment]
Insyaallah weekend ini lanjutin ke verifikasi email

**Comment by algonacci** [comment]
> Insyaallah weekend ini lanjutin ke verifikasi email

Oke siap, saya assign dulu yaa biar gada yg ngerjain ini juga 😄 

Take your time

**Comment by AaEzha** [comment]
alhamdulillah #17 dan #18

**Comment by algonacci** [comment]
Wahhh thanks berat mas @AaEzha dan juga mas @NurfitraPujo 

Akhirnya kelar juga sejak 1 minggu di-open issue😄 

Saya close yaa issuenya, kalau ada update nanti akan saya open lagi. Sekali lagi terima kasih banyak kontribusinya 👍
