### ISSUE TITLE
fix: Make better UI on Navbar

### ISSUE THREAD

**Issue by doniwirawan** [OpenProjects-id/KawanData#5]
i wonder about the footer, i want to improve it. Also i want to make some bar kinda like this: [https://vercel.com/blog](url) to promote this repo

**Comment by doniwirawan** [comment]
i mean bar on top of navbar

**Comment by algonacci** [comment]
Approved. You can work on the UI design of the navbar now.

Don't forget to make a to do list so I know the work progress 😄

**Comment by algonacci** [comment]
> Approved. You can work on the UI design of the navbar now.
> 
> Don't forget to make a to do list so I know the work progress 😄

And also the UI Design of the Footer.

Just contact or mentioned me if you need any assets such as logo or etc.

**Comment by doniwirawan** [comment]
can you educate me about how to make to-do list, is that in the project board? or where?

**Comment by doniwirawan** [comment]
i already work on that but how do i move that card in project board to "doing"

**Comment by algonacci** [comment]
> 

I worry that only can be done by the administrator/owner which is me.

Can't you move the project's progress by drag and dropping them from Product Backlog to Doing column?

**Comment by doniwirawan** [comment]
no i can't

**Comment by doniwirawan** [comment]
finished it already and i already make a pull request

**Comment by algonacci** [comment]
Thanks for your PR, please keep contributing on our projects yaa mas 😄 

I'll close this issue, Thank you @doniwirawan
